version: '3.8'

services:
  arai-app:
    build: .
    container_name: arai-container
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - arai-data:/app/data
    restart: unless-stopped
    networks:
      - arai-network

volumes:
  arai-data:
    driver: local

networks:
  arai-network:
    driver: bridge